// MAIN
export const LOGIN_ADMIN = 'LOGIN_ADMIN';
export const LOGAUTH_ADMIN = 'LOGIN_ADMIN';

export const GET_CURRENT_ADMIN = 'GET_CURRENT_ADMIN';

export const SET_CURRENT_ADMIN = 'SET_CURRENT_ADMIN';
export const SET_ERROR_MESSAGE_LOGIN = 'SET_ERROR_MESSAGE_LOGIN';


// EVENTS
export const GET_EVENTS = 'GET_EVENTS';
export const GET_EDITE_EVENT = 'GET_EDITE_EVENT';

export const SET_EVENT = 'SET_EVENT';
export const SET_EVENT_COUNT = 'SET_EVENT_COUNT';
export const SET_EDITE_EVENT = 'SET_EDITE_EVENT';
export const SET_ERROR_MESSAGE_EVENT = 'SET_ERROR_MESSAGE_EVENT';

export const CREATE_EVENT = 'CREATE_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';

export const DELETE_EVENT = 'DELETE_EVENT';
export const DELETE_SELECTED_EVENT = 'DELETE_SELECTED_EVENT';


// USERS
export const GET_USERS = 'GET_USERS';
export const GET_EDITE_USER = 'GET_EDITE_USER';

export const SET_USER = 'SET_USER';
export const SET_USER_COUNT = 'SET_USER_COUNT';
export const SET_EDITE_USER = 'SET_EDITE_USER';
export const SET_ERROR_MESSAGE_USERS = 'SET_ERROR_MESSAGE_USERS';

export const ADD_USER = 'ADD_USER';
export const EDITE_USER = 'EDITE_USER';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_SELECTED_USERS = 'DELETE_SELECTED';



// TYPES
export const GET_TYPES = 'GET_TYPES';
export const GET_TYPE_BY_ID = 'GET_TYPE_BY_ID';

export const SET_TYPES = 'SET_TYPES';
export const SET_TYPE_COUNT = 'SET_TYPE_COUNT';
export const SET_EDITE_TYPE = 'SET_EDITE_TYPE';
export const SET_ERROR_MESSAGE_TYPE = 'SET_ERROR_MESSAGE_TYPE';

export const UPDATE_TYPE = 'UPDATE_TYPE';
export const CREATE_TYPE = 'CREATE_TYPE';

export const DELETE_TYPE = 'DELETE_TYPE';
export const DELETE_SELECTED_TYPE = 'DELETE_SELECTED_TYPE';


// REPORT
export const GET_REPORTS = 'GET_REPORTS';
export const GET_REPORTS_BY_ID = 'GET_REPORTS_BY_ID';

export const SET_REPORTS = 'SET_REPORTS';
export const SET_EDITE_REPORT = 'SET_EDITE_REPORT';
export const SET_ERROR_MESSAGE_REPORT = 'SET_ERROR_MESSAGE_REPORT';


export const EDITE_REPORTS = 'EDITE_REPORTS';
export const DELETE_REPORT = 'DELETE_REPORT';

// REPORT EVENTS
export const GET_REPORT_EVENTS = 'GET_REPORT_EVENTS';

export const SET_REPORT_EVENTS = 'SET_REPORT_EVENTS';
export const SET_REPORT_EVENT_COUNT = 'SET_REPORT_EVENT_COUNT';

export const APPROVE_REPORT_EVENT = 'APPROVE_REPORT_EVENT';

//REPORT COMMENTS
export const GET_REPORTS_COMMENT = 'GET_REPORTS_COMMENT';

export const SET_REPORT_COMMENTS = 'SET_REPORT_COMMENTS';
export const SET_REPORT_COMMENT_COUNT = 'SET_REPORT_COMMENT_COUNT';

export const APPROVE_REPORT_COMMENT = 'APPROVE_REPORT_COMMENT';
//////////

export const SET_NOTIFICATION_INFO = 'SET_NOTIFICATION_INFO';